# Generated by Django 5.0.5 on 2024-05-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите наименование категории', null=True, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='DjangoORM/ProductPictures')),
                ('price', models.CharField(help_text='Введите цену', verbose_name='Цена')),
                ('create_at', models.DateTimeField(help_text='Введите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(help_text='Введите дату создания последнего изменения', verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', 'description', 'category', 'price', 'create_at', 'updated_at'],
            },
        ),
    ]
