# Generated by Django 5.0.5 on 2024-05-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_product_manufactured_at_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufactured_at',
        ),
    ]
