# Generated by Django 5.0.5 on 2024-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_alter_product_create_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату создания последнего изменения', null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
