# Generated by Django 5.0.5 on 2024-06-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия товара', 'verbose_name_plural': 'Версии товара'},
        ),
    ]
