# Generated by Django 5.0.5 on 2024-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0010_delete_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'description', 'category', 'price', 'create_at', 'updated_at'], 'permissions': [('can_cancel_publication', 'Может отменять публикацию продукта')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
