# Generated by Django 5.0.5 on 2024-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0011_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'description', 'category', 'price', 'create_at', 'updated_at'], 'permissions': [('can_cancel_publication', 'Может отменять публикацию продукта'), ('can_change_description_any', 'Может менять описание любого продукта'), ('can_change_category_any', 'Может менять категорию любого продукта')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
